load("//bazel:java.bzl", "java_library_auto", "java_test_auto")

package(default_visibility = ["//visibility:public"])

java_library_auto(
    deps = [
        "//fade/common",
        "//fade/context"
    ],
)

java_test_auto()
