name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build & test
        uses: docker://ghcr.io/lewish/lewish-builder:latest
        with:
          args: bash -c "bazel test --build_tests_only ..."
